name: teaching
channels:
  - conda-forge
dependencies:
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - bleach=6.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - flit-core=3.8.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.12.0
  - ipykernel=6.16.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jpeg=9e
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.5.1
  - jupyter_core=4.11.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=13.0.1
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.08
  - libgfortran5=11.3.08
  - libglib=2.74.1
  - libiconv=1.17
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm13=13.0.1
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13004
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.5.2
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.88
  - numpy=1.21.6
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=23.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5003
  - pillow=9.2.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.3
  - pthread-stubs=0.4001
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - python=3.7.1200_cpython
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7=3_cp37m
  - pyzmq=24.0.1
  - qt-main=5.15.8
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=67.3.2
  - sip=6.7.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - unicodedata2=14.0.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.14.0
  - zstd=1.5.2
  - pip:
      - appdirs==1.4.4
      - atomicwrites==1.4.1
      - cobra==0.26.2
      - cplex==12.10.0.0
      - depinfo==1.7.0
      - diskcache==5.4.0
      - escher==1.7.3
      - future==0.18.3
      - h11==0.14.0
      - httpcore==0.16.3
      - httpx==0.23.3
      - inspyred==1.0.1
      - ipywidgets==7.7.3
      - jinja2==2.11.3
      - jmetalpy==1.5.5
      - joblib==1.2.0
      - jsonschema==3.2.0
      - jupyterlab-widgets==1.1.2
      - markdown-it-py==2.2.0
      - markupsafe==2.0.1
      - mdurl==0.1.2
      - mewpy==0.1.25
      - mistune==0.8.4
      - more-itertools==9.0.0
      - mpmath==1.2.1
      - nbclient==0.5.13
      - nbconvert==6.4.5
      - networkx==2.6.3
      - optlang==1.6.1
      - pandas==1.3.5
      - patsy==0.5.3
      - plotly==5.13.0
      - pluggy==0.13.1
      - py==1.11.0
      - pydantic==1.10.5
      - pytest==4.6.11
      - python-libsbml==5.19.7
      - pytz==2022.7.1
      - reframed==1.2.1
      - rfc3986==1.5.0
      - rich==13.3.1
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - scipy==1.7.3
      - statsmodels==0.13.5
      - swiglpk==5.0.8
      - sympy==1.10.1
      - tdqm==0.0.1
      - tenacity==8.2.1
      - testpath==0.6.0
      - tqdm==4.64.1
      - widgetsnbextension==3.6.2
