name: teaching
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.5.3
  - numpy=1.21.6
  - pip=23.0.1
  - python=3.7
  - pip:
      - cobra==0.26.2
      - cplex==12.10.0.0
      - escher==1.7.3
      - inspyred==1.0.1
      - jmetalpy==1.5.5
      - markupsafe==2.0.1
      - mewpy==0.1.25
      - networkx==2.6.3
      - optlang==1.6.1
      - pandas==1.3.5
      - python-libsbml==5.19.7
      - reframed==1.2.1
      - scipy==1.7.3
      - statsmodels==0.13.5
      - swiglpk==5.0.8
      - sympy==1.10.1
